<?php

return [
    [
        'name'    => 'viptips',
        'title'   => '列表页面提示文字',
        'type'    => 'text',
        'content' => [],
        'value'   => '请选择你需要购买或升级的VIP',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'paytypelist',
        'title'   => '支付方式',
        'type'    => 'checkbox',
        'content' => [
            'wechat' => '微信支付',
            'alipay' => '支付宝支付',
            'balance' => '余额支付',
        ],
        'value'   => 'wechat,alipay,balance',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'defaultpaytype',
        'title'   => '默认支付方式',
        'type'    => 'radio',
        'content' => [
            'wechat' => '微信支付',
            'alipay' => '支付宝支付',
            'balance' => '余额支付',
        ],
        'value'   => 'wechat',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'ordercreatelimit',
        'title'   => '订单生成限制',
        'type'    => 'radio',
        'content' => [
            1 => '限制',
            0 => '不限制',
        ],
        'value'   => '0',
        'rule'    => 'required',
        'msg'     => '',
        'tip'     => '是否限制未支付相同金额的订单在30分钟内只生成一次',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'usersidenav',
        'title'   => '会员中心边栏模块',
        'type'    => 'checkbox',
        'content' => [
            'viplist' => 'VIP列表',
            'record'  => 'VIP记录',
        ],
        'value'   => 'viplist,record',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '会员中心边栏模块',
        'ok'      => '',
        'extend'  => '',
    ],
    [
        'name'    => 'expirecheckmode',
        'title'   => '过期判断模式',
        'type'    => 'radio',
        'content' => [
            'autotask' => '定时任务模式(推荐，需添加定时任务)',
            'hook'     => 'Hook模式(不推荐，仅在用户登录且刷新页面时判断)',
        ],
        'value'   => 'hook',
        'rule'    => '',
        'msg'     => '',
        'tip'     => '用于VIP过期判断模式，添加定时任务的方法请参考文档',
        'ok'      => '',
        'extend'  => '',
    ],
];
