<?php

return [
    [
        'name' => 'enterimg',
        'title' => '入口图片',
        'type' => 'image',
        'content' => [],
        'value' => '/uploads/20220428/e897f803802bb4bfee2eadf3a127c3d7.png',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    8 => [
        'name' => 'logo',
        'title' => '商城LOGO',
        'type' => 'image',
        'content' => [],
        'value' => '/uploads/20220428/e897f803802bb4bfee2eadf3a127c3d7.png',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    1 => [
        'name' => 'scorestatus',
        'title' => '开启积分商城',
        'type' => 'radio',
        'content' => [
            1 => '启用',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    2 => [
        'name' => 'open_clear',
        'title' => '清理订单',
        'type' => 'radio',
        'content' => [
            1 => '启用',
            0 => '关闭',
        ],
        'value' => '1',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    3 => [
        'name' => 'open_clear_time',
        'title' => '清理间隔（分钟）',
        'type' => 'number',
        'content' => '',
        'value' => '60',
        'rule' => 'required',
        'msg' => '',
        'tip' => '24小时内未完成付款将会关闭订单',
        'ok' => '',
        'extend' => '',
    ],
    4 => [
        'name' => 'order_out_time',
        'title' => '订单删除',
        'type' => 'number',
        'content' => '',
        'value' => '60',
        'rule' => '',
        'msg' => '',
        'tip' => '未付款订单x天后直接删除。',
        'ok' => '',
        'extend' => '',
    ],
    5 => [
        'name' => 'order_prefix',
        'title' => '订单前缀',
        'type' => 'string',
        'content' => '',
        'value' => 'SN',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    6 => [
        'name' => 'domain',
        'title' => '绑定二级域名前缀',
        'type' => 'string',
        'content' => [],
        'value' => '',
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    7 => [
        'name' => 'rewrite',
        'title' => '伪静态',
        'type' => 'array',
        'content' => [],
        'value' => [
            'goods/index' => '/leescore/goods$',
            'order/index' => '/leescore/order$',
            'index/index' => '/score$',
            'address/index' => '/address$',
        ],
        'rule' => '',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
